### ISSUE TITLE
the document about `attachToObject` is super misleading

### ISSUE THREAD

**Issue by cyan33** [happy-codes/happy-getter#3]
In the README, I found it hard to get what you mean about the function `attachToObject`, until I read the source code. And the variable `hg` is also confusing and meaningless.

I suggest making it straight-forward and less confusing by writing like this:

> the function `attachToObject` is a mixin to enable the object itself to have the getter method, so that you could call `getter` on the object itself:
```js
var myObj = { name: 'John' }
attachToObject('getter')

// then you could do
myObj.getter('name')  // John
```

**Comment by cyan33** [comment]
also I recommend changing the function name to `attachGetter`, since in the source code you can only attach the getter function itself. And `attachToObject` is a much more generic name.

**Comment by yujiangshui** [comment]
yes, you are right. I fixed and thank you.
